### ISSUE TITLE
Do not work as gmail required phone number verification now

### ISSUE THREAD

**Issue by zjavaid1981** [khaouitiabdelhakim/Gmail-Creation-Automation-Python#4]
There is no option to skip phone number validation so this script do not work anymore

**Comment by khaouitiabdelhakim** [comment]
Yes, wiating to find somehow to bypass this problem! do you have any suggestions bro?

**Comment by niks17** [comment]
Maybe you can integrate sms pool API .

**Comment by qwaider** [comment]
suppose that we can do this one step manually .. can you adjust the code for that?

**Comment by FruitfulApproach** [comment]
The solution is to have a step where your users have to use their phone obviously.  If you can't jive with that, then you are doing something illegal.  Please stop scamming people, if that is the case.  I think the script is perfect as is.  If you can't get it to work, you are not mature enough to use this code, and are probably abusing it or some other people.  I have a legitimate reason to create an account for the job seekers using my app.  And I won't allow them to create more than say 1-3 accounts.    Stop ruining the world for everyone else.  Thanks! 😠
