### ISSUE TITLE
not working showing this eror

### ISSUE THREAD

**Issue by darkstudy45** [khaouitiabdelhakim/Gmail-Creation-Automation-Python#6]
something opening behind and closing in instant 
![image](https://github.com/khaouitiabdelhakim/Gmail-Creation-Automation-Python/assets/114846213/0fc8a08e-209a-47e6-84c3-ce1ed38b9842)

**Comment by sycl0** [comment]
I got the same error

**Comment by sycl0** [comment]
i think cuz now you can't skip phone number validation

**Comment by khaouitiabdelhakim** [comment]
Exactly, it might be due to the phone verification skip button.
